version: '3.8'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: bulletin_board
      POSTGRES_USER: sampleuser
      POSTGRES_PASSWORD: hogehoge
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
